---
- name: Deploy Docker Image to Container
  hosts: all
  vars:
    ansible_python_interpreter: /opt/homebrew/bin/python3
  tasks:
    - name: Pull Docker Image
      shell: |
        docker pull santhil/miniproj

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: tempimages
        image: santhil/miniproj
        state: started
        tty: yes
        interactive: yes
